"""Add theme column to forms table

Revision ID: f94b2d03aa3b
Revises: <generisani_hash_iz_komande>
Create Date: 2025-10-13 13:53:20.512864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94b2d03aa3b'
down_revision: Union[str, Sequence[str], None] = '<generisani_hash_iz_komande>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('theme', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'theme')
    # ### end Alembic commands ###
